import { cache } from 'react';
import { getListingBySlug, getLiveListingCards } from '@/marketplace/db/queries/listings';
import { getListingSpecs, buildSpecSheet, getCardSpecs } from '@/marketplace/db/queries/specs';
import { getKindsWithOptions } from '@/marketplace/db/queries/attributes';
import { normalizeListing, localized } from '@/marketplace/lib/listing';

/**
 * Everything the compare page reads.
 *
 * Reads the query layer directly rather than fetching /api/marketplace/* — the
 * page is a server component, so an HTTP hop to our own route would cost a
 * round trip and a connection for nothing. Same rule the listing page follows.
 *
 * ── Why the cars are in the URL and not in a cookie ─────────────────────────
 *
 * A comparison is a THING, not a session state: "these two, side by side" is
 * worth sending to someone, worth a search engine indexing, and worth coming
 * back to tomorrow. Held in a cookie it is none of those — the link a buyer
 * pastes into WhatsApp opens on whatever the recipient last compared.
 *
 * So the slugs are path segments, exactly as the main site does it
 * (/compare-cars/[[...slugs]]), and the page is a plain GET anybody can share.
 */

/**
 * Three, the same ceiling the main site uses.
 *
 * Not a layout limit — four columns fit on a desktop — but a consistency one:
 * a buyer who crosses from alromaihcars.com should not find that the same
 * gesture allows a different number of cars. It is also the point past which
 * a phone's column is too narrow to read a value in.
 */
export const MAX_COMPARE = 3;

/**
 * Slugs, cleaned.
 *
 * Deliberately NOT validated against a character class. Marketplace slugs are
 * generated by slugify(), which KEEPS Arabic letters (see lib/slug.js), so an
 * `/^[a-z0-9-]+$/` guard — the obvious one to write — would reject every
 * Arabic-titled listing on the site and render its comparison empty with no
 * error anywhere.
 *
 * The real validation is the lookup: a slug that names nothing comes back null
 * and is dropped. This only has to stop the two things that are never a slug —
 * a path traversal and an unbounded string.
 */
export function cleanSlugs(slugs) {
  const out = [];

  for (const raw of Array.isArray(slugs) ? slugs : []) {
    let s = String(raw ?? '');
    // A catch-all segment arrives percent-encoded for anything non-ASCII, which
    // is most Arabic slugs.
    try {
      s = decodeURIComponent(s);
    } catch {
      /* Malformed encoding: compare what was actually typed rather than 500. */
    }

    s = s.trim().toLowerCase();

    if (!s || s.length > 120 || s.includes('/') || s.includes('\\')) continue;
    if (out.includes(s)) continue;

    out.push(s);
    if (out.length >= MAX_COMPARE) break;
  }

  return out;
}

/**
 * One car, with its spec sheet. Memoised per request so generateMetadata and
 * the page body share a single read — without cache() every comparison would
 * run its queries twice.
 */
/**
 * The catalog, once per request.
 *
 * getKindsWithOptions is two queries and knows nothing about any particular
 * car, but it was being called from inside loadCar — so a three-car comparison
 * fetched the same catalog three times and waited for it three times. cache()
 * here collapses that to one fetch that all three cars await.
 *
 * Wrapped locally rather than by editing the query itself: the memo lasts one
 * request, and this is the page that needs it N times.
 */
const loadKinds = cache(() => getKindsWithOptions().catch(() => []));

const loadCar = cache(async (slug, locale) => {
  /* Started BEFORE the row is looked up, not after. The catalog does not
     depend on the car, so making it wait for the slug lookup added a whole
     round trip to the front of every column for nothing. */
  const kindsPromise = loadKinds();

  const row = await getListingBySlug(slug).catch(() => null);
  if (!row) return null;

  // Both optional and independent: a car whose specs or catalog fail to load
  // still belongs in the table, with blank cells rather than no column.
  const [specRows, kinds] = await Promise.all([
    getListingSpecs(row.id).catch(() => []),
    kindsPromise,
  ]);

  /**
   * Catalog attributes — fuel, transmission, body type — resolved against the
   * same table the listing form writes, exactly as the listing page does it.
   * Hardcoding the labels here would mean a fifth fuel type showed as the raw
   * slug `lpg` on this page and correctly everywhere else.
   */
  const attributes = row.attributes ?? {};
  const kindFacts = kinds
    .map((k) => {
      const slug = attributes[k.kind];
      if (!slug) return null;
      const option = k.options.find((o) => o.slug === slug);
      return {
        kind: k.kind,
        label: localized(k.name, locale) || k.kind,
        icon: k.iconUrl ?? null,
        value: (option && localized(option.name, locale)) || slug,
      };
    })
    .filter(Boolean);

  return {
    ...normalizeListing(row, locale),
    kindFacts,
    specSheet: buildSpecSheet(specRows, locale),
    // Read off the raw row: normalizeListing does not carry these, and they are
    // three of the things a buyer most wants lined up.
    warrantyMonths: row.warranty_months ?? null,
    countryOfOrigin: row.country_of_origin || null,
    hasTestDrive: row.has_test_drive === true,
    trim: localized(row.car_trims?.name, locale) || null,
  };
});

/** True when the cars that HAVE this row do not agree. */
function disagrees(values, carIds) {
  const present = carIds.map((id) => values[id]).filter((v) => v != null && v !== '');
  // One car is not a disagreement, and neither is one answer given twice.
  if (present.length < 2) return false;
  return new Set(present.map((v) => String(v).trim().toLowerCase())).size > 1;
}

/**
 * The rows above the spec sheet: what a buyer decides on before reading a
 * specification.
 *
 * Vendor is FIRST after price and has no equivalent on the main site — it is
 * the whole difference between comparing two cars and comparing two offers.
 * The same model from two showrooms is the commonest comparison this page will
 * ever be asked for, and the seller is then the only thing that differs.
 */
function buildOverview(cars, locale) {
  const t = (ar, en) => (locale === 'ar' ? ar : en);
  const ids = cars.map((c) => c.id);

  const rows = [
    {
      key: 'price',
      label: t('السعر', 'Price'),
      // The price a buyer actually pays — normalizeListing has already applied
      // any running offer (schema.sql §25), so a discounted car cannot show one
      // number here and another on its own page.
      values: Object.fromEntries(cars.map((c) => [c.id, c.priceLabel])),
      // Compared on the NUMBER, not the formatted string: "٣٥٬٠٠٠ ر.س" and
      // "35,000 SAR" are the same price written two ways.
      compare: Object.fromEntries(cars.map((c) => [c.id, c.price])),
      // What lets the cheapest cell be marked. Only meaningful where every car
      // quotes a price.
      best: 'low',
    },
    {
      key: 'vendor',
      label: t('البائع', 'Seller'),
      values: Object.fromEntries(cars.map((c) => [c.id, c.vendor?.name ?? null])),
    },
    {
      key: 'city',
      label: t('المدينة', 'City'),
      values: Object.fromEntries(cars.map((c) => [c.id, c.city || null])),
    },
    {
      key: 'brand',
      label: t('الماركة', 'Brand'),
      values: Object.fromEntries(cars.map((c) => [c.id, c.brand?.name ?? null])),
    },
    {
      key: 'trim',
      label: t('الفئة', 'Trim'),
      values: Object.fromEntries(cars.map((c) => [c.id, c.trim])),
    },
    {
      key: 'warranty',
      label: t('الضمان', 'Warranty'),
      values: Object.fromEntries(
        cars.map((c) => [
          c.id,
          c.warrantyMonths ? t(`${c.warrantyMonths} شهراً`, `${c.warrantyMonths} months`) : null,
        ])
      ),
      compare: Object.fromEntries(cars.map((c) => [c.id, c.warrantyMonths])),
      best: 'high',
    },
    {
      key: 'origin',
      label: t('بلد المنشأ', 'Country of origin'),
      values: Object.fromEntries(cars.map((c) => [c.id, c.countryOfOrigin])),
    },
    {
      key: 'testDrive',
      label: t('قيادة تجريبية', 'Test drive'),
      values: Object.fromEntries(
        cars.map((c) => [c.id, c.hasTestDrive ? t('متاحة', 'Available') : null])
      ),
    },
  ];

  /**
   * Every catalog attribute any of these cars carries, in catalog order.
   *
   * Built from the union rather than from the first car: two cars rarely fill
   * in the same set, and keying off one of them would silently drop a fact the
   * other has — which on a comparison page reads as "neither has it".
   */
  const kindRows = [];
  const seen = new Set();
  for (const car of cars) {
    for (const fact of car.kindFacts) {
      if (seen.has(fact.kind)) continue;
      seen.add(fact.kind);
      kindRows.push({
        key: `kind:${fact.kind}`,
        label: fact.label,
        icon: fact.icon,
        values: Object.fromEntries(
          cars.map((c) => [c.id, c.kindFacts.find((f) => f.kind === fact.kind)?.value ?? null])
        ),
      });
    }
  }

  return [...rows, ...kindRows]
    // A row no car answers is a row of dashes.
    .filter((r) => ids.some((id) => r.values[id] != null && r.values[id] !== ''))
    .map((r) => ({
      ...r,
      differs: disagrees(r.compare ?? r.values, ids),
      winner: r.best ? pickWinner(r, ids) : null,
    }));
}

/**
 * The id of the car holding the best number in this row, or null.
 *
 * Null unless EVERY car answers and exactly one of them is best. A "cheapest"
 * badge awarded because the other seller left the field blank is not a fact
 * about the cars, and a tie has no winner to mark.
 */
function pickWinner(row, ids) {
  const nums = ids.map((id) => {
    const raw = row.compare?.[id];
    // NOT Number(raw) alone: Number(null) and Number("") are both 0, which
    // is finite — so a car with no price would pass the guard below and then
    // win "cheapest" outright, because 0 is smaller than every real price.
    return raw == null || raw === "" ? NaN : Number(raw);
  });
  if (nums.some((n) => !Number.isFinite(n))) return null;
  if (nums.length < 2) return null;

  const target = row.best === 'low' ? Math.min(...nums) : Math.max(...nums);
  const holders = ids.filter((_, i) => nums[i] === target);
  return holders.length === 1 ? holders[0] : null;
}

/**
 * The spec sheets, merged into one table.
 *
 * The hard part of a comparison is that the cars do NOT have the same specs:
 * one seller filled in twelve, another four, and a third uses a category the
 * others do not. So categories and attributes are both a UNION in first-seen
 * order, and a car that lacks a row gets an empty cell rather than being
 * dropped from it.
 *
 * Keyed on the spec's own slug (falling back to its id) rather than on the
 * translated label — two sellers using the same attribute must land on one row
 * even when the page is being read in a language one of them did not fill in.
 */
function mergeSheets(cars) {
  const ids = cars.map((c) => c.id);
  const groups = new Map();

  for (const car of cars) {
    for (const group of car.specSheet ?? []) {
      if (!groups.has(group.key)) {
        groups.set(group.key, {
          key: group.key,
          name: group.name,
          icon: group.icon,
          items: new Map(),
        });
      }
      const target = groups.get(group.key);

      for (const item of group.items ?? []) {
        const key = item.slug || item.id;
        if (!target.items.has(key)) {
          target.items.set(key, {
            key,
            label: item.label,
            icon: item.icon,
            unit: item.unit,
            // A yes/no spec renders as a tick or a cross rather than the
            // word, which is what makes a column of them scannable.
            displayType: item.displayType ?? null,
            // Which of the two blocks this row belongs to.
            isKey: Boolean(item.isKey || item.showOnCard),
            values: {},
          });
        }
        const row = target.items.get(key);
        // The first car to carry this spec names it. A later car whose label is
        // blank in this locale must not overwrite a good one.
        if (!row.label && item.label) row.label = item.label;
        if (!row.icon && item.icon) row.icon = item.icon;
        if (!row.displayType && item.displayType) row.displayType = item.displayType;
        // Flagged key by ANY car is key: the flag lives on the catalog
        // attribute, so two cars can only disagree when one of them was
        // saved before the flag was set.
        if (item.isKey || item.showOnCard) row.isKey = true;
        row.values[car.id] = item.value ?? null;
      }
    }
  }

  return [...groups.values()].map((g) => ({
    key: g.key,
    name: g.name,
    icon: g.icon,
    items: [...g.items.values()].map((item) => ({
      ...item,
      differs: disagrees(item.values, ids),
    })),
  }));
}

/**
 * The whole comparison, for a list of slugs.
 *
 * Slugs that name nothing are DROPPED rather than 404ing the page: a link with
 * one stale car in it should still compare the others, and the picker is right
 * there to add a replacement. `missing` is returned so the page can say so
 * instead of quietly showing fewer cars than the URL asked for.
 */
export const getComparison = cache(async (slugs, locale = 'ar') => {
  const wanted = cleanSlugs(slugs);
  if (!wanted.length) {
    return { cars: [], overview: [], keySpecs: [], groups: [], missing: [], slugs: [] };
  }

  const loaded = await Promise.all(wanted.map((s) => loadCar(s, locale)));
  const cars = loaded.filter(Boolean);
  const missing = wanted.filter((_, i) => !loaded[i]);

  /* The card's own icon row, for the columns at the top. Failing softly:
     a card without its spec row is still a card, and a comparison should
     not be lost over a decorative band. */
  const cardSpecs = await getCardSpecs(cars.map((c) => c.id), locale, 4).catch(() => new Map());
  for (const car of cars) car.cardSpecs = cardSpecs.get(car.id) ?? [];

  const merged = mergeSheets(cars);

  /* The flagged handful, lifted out of their categories and shown above the
     sheet — and REMOVED from it, so no row is printed twice. */
  const keySpecs = merged.flatMap((g) => g.items).filter((i) => i.isKey);
  const groups = merged
    .map((g) => ({ ...g, items: g.items.filter((i) => !i.isKey) }))
    .filter((g) => g.items.length > 0);

  return {
    cars,
    overview: buildOverview(cars, locale),
    keySpecs,
    groups,
    missing,
    slugs: cars.map((c) => c.slug),
  };
});

/**
 * The cars a visitor can add, for the picker.
 *
 * CAPPED, and the cap is the honest limit of the picker: the dialog filters
 * what it is given in the browser, so a car past this many is not findable
 * there. Sixty covers a marketplace of this size several times over; the day
 * it does not, the search has to move to the server rather than the number
 * being raised again.
 *
 * Newest first, and excludes what is already being compared so the list never
 * offers a car that would do nothing.
 */
export const getPickableCars = cache(async (excludeSlugs = [], locale = 'ar', limit = 60) => {
  const { items } = await getLiveListingCards({ type: 'car', sort: 'newest', limit: limit + MAX_COMPARE })
    .catch(() => ({ items: [] }));

  const exclude = new Set(excludeSlugs);
  const cars = items
    .map((row) => normalizeListing(row, locale))
    .filter((c) => c && !exclude.has(c.slug))
    .slice(0, limit);

  const cardSpecs = await getCardSpecs(cars.map((c) => c.id), locale, 4).catch(() => new Map());
  for (const car of cars) car.cardSpecs = cardSpecs.get(car.id) ?? [];

  return cars;
});

/** Shared by the page and its metadata, so the two can never word it differently. */
export function comparisonTitle(cars, locale = 'ar') {
  const vs = locale === 'ar' ? ' مقابل ' : ' vs ';
  return cars.map((c) => c.title).filter(Boolean).join(vs);
}
