/**
 * GENERATED by src/marketplace/db/build-catalog-templates.cjs — do not edit.
 *
 * Static imports on purpose: this is what puts the templates inside the
 * deployed bundle, so a vendor never has to build anything to install one.
 */

import manifest from './index.json';
import brands from './brands.json';
import models from './models.json';
import trims from './trims.json';
import years from './years.json';
import colors from './colors.json';
import specifications from './specifications.json';
import offerNames from './offer-names.json';

export const MANIFEST = manifest;

export const TEMPLATES = {
  brands,
  models,
  trims,
  years,
  colors,
  specifications,
  'offer-names': offerNames,
};
